### ISSUE TITLE
Access to the source code

### ISSUE THREAD

**Issue by zyy0721** [Lycheus/SHORE#1]
Hi, is the source code of the project still accessible ?

**Comment by Lycheus** [comment]
Yes, the source code is now fully accessible.

**Comment by zyy0721** [comment]
> Yes, the source code is now fully accessible.

Yeah, it is! Thanks a lot, it is very kind of you to do so.

**Comment by Lycheus** [comment]
Cheers mate! 

The thread is close as the issue is solved.
